# Generated by Django 5.0.1 on 2024-01-19 15:20

import userlog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(default='profilepic\\profile.jpg', upload_to=userlog.models.profile_pic_file_path),
        ),
    ]
