# Generated by Django 5.0.1 on 2024-01-25 06:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseDescrip',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
